const areaConditionData = {
  title: 'エリア',
  name:"area",
  data: [
    { value: 'SA11', key: '東京' },
    { value: 'SA12', key: '神奈川' },
    { value: 'SA13', key: '埼玉' },
    { value: 'SA14', key: '千葉' },
    { value: 'SA15', key: '茨城' },
    { value: 'SA16', key: '栃木' },
    { value: 'SA17', key: '群馬' },
    { value: 'SA21', key: '滋賀' },
    { value: 'SA22', key: '京都' },
    { value: 'SA23', key: '大阪' },
    { value: 'SA24', key: '兵庫' },
    { value: 'SA25', key: '奈良' },
    { value: 'SA26', key: '和歌山' },
    { value: 'SA31', key: '岐阜' },
    { value: 'SA32', key: '静岡' },
    { value: 'SA33', key: '愛知' },
    { value: 'SA34', key: '三重' },
    { value: 'SA41', key: '北海道' },
    { value: 'SA51', key: '青森' },
    { value: 'SA52', key: '岩手' },
    { value: 'SA53', key: '宮城' },
    { value: 'SA54', key: '秋田' },
    { value: 'SA55', key: '山形' },
    { value: 'SA56', key: '福島' },
    { value: 'SA61', key: '新潟' },
    { value: 'SA62', key: '富山' },
    { value: 'SA63', key: '石川' },
    { value: 'SA64', key: '福井' },
    { value: 'SA65', key: '山梨' },
    { value: 'SA66', key: '長野' },
    { value: 'SA71', key: '鳥取' },
    { value: 'SA72', key: '島根' },
    { value: 'SA73', key: '岡山' },
    { value: 'SA74', key: '広島' },
    { value: 'SA75', key: '山口' },
    { value: 'SA81', key: '徳島' },
    { value: 'SA82', key: '香川' },
    { value: 'SA83', key: '愛媛' },
    { value: 'SA84', key: '高知' },
    { value: 'SA91', key: '福岡' },
    { value: 'SA92', key: '佐賀' },
    { value: 'SA93', key: '長崎' },
    { value: 'SA94', key: '熊本' },
    { value: 'SA95', key: '大分' },
    { value: 'SA96', key: '宮崎' },
    { value: 'SA97', key: '鹿児島' },
    { value: 'SA98', key: '沖縄' },
  ],
};

export default areaConditionData