const shopData = [
  {
    id: 'J000014013',
    title: '居酒屋 焼肉 甘太郎 天王寺店',
    area: '大阪 天王寺 天王寺駅',
    genre: '居酒屋',
    subgenre: '焼肉・ホルモン',
    budget: '2800円',
    catchword: '種類豊富な居酒屋メニュー 天王寺駅直結の好立地♪',
    tags: ['コース有り', 'ランチ営業あり', 'wifiあり'],
    url: 'https://www.hotpepper.jp/strJ000014013/?vos=nhppalsa000016',
  },
  {
    id: 'J000013999',
    title: '甘太郎 なんば店',
    area: '大阪 心斎橋・なんば・南船場・堀江 難波',
    genre: '居酒屋',
    subgenre: '和食',
    budget: '完全個室16名様12名様有ります 単価2500円',
    catchword: '人気のプライベート空間 ☆居酒屋メニュー☆',
    tags: ['コース有り', 'wifiあり'],
    url: 'https://www.hotpepper.jp/strJ000013999/?vos=nhppalsa000016',
  },
  {
    id: 'J000773173',
    title: '手作り居酒屋 甘太郎 新宿三丁目店',
    area: '東京 新宿 新宿三丁目',
    genre: '居酒屋',
    subgenre: '和食',
    budget: '2,500円',
    catchword: '人気の駅近居酒屋で飲み会 ☆居酒屋メニュー☆',
    tags: ['コース有り', 'wifiあり', '飲み放題あり', '食べ放題あり'],
    url: 'https://www.hotpepper.jp/strJ000773173/?vos=nhppalsa000016',
  },
  {
    id: 'J000000666',
    title: '甘太郎 秋葉原店',
    area: '東京 神田・神保町・秋葉原・御茶ノ水 秋葉原',
    genre: '焼肉・ホルモン',
    subgenre: '居酒屋',
    budget: '2500円',
    catchword: '駅チカ好立地 ☆居酒屋メニュー☆',
    tags: ['コース有り', 'wifiあり'],
    url: 'https://www.hotpepper.jp/strJ000000666/?vos=nhppalsa000016',
  },
  {
    id: 'J001187438',
    title: '甘太郎 横浜西口本店',
    area: '神奈川 横浜 横浜駅',
    genre: '居酒屋',
    subgenre: '居酒屋',
    budget: '2200円★飲み放題1100円(税込)から',
    catchword: '☆居酒屋メニュー☆ 昼飲み推奨！12時～OPEN',
    tags: ['コース有り', 'ランチ営業あり', 'wifiあり'],
    url: 'https://www.hotpepper.jp/strJ001187438/?vos=nhppalsa000016',
  },
  {
    id: 'J001219010',
    title: '本八幡 居酒屋 元気太郎 本店',
    area: '千葉 船橋･津田沼･市川･本八幡･中山 本八幡',
    genre: '居酒屋',
    subgenre: '居酒屋',
    budget: '2500円',
    catchword: 'GoToトラベル食事券対象店 ＼全席喫煙可能です★／',
    tags: ['コース有り', 'ランチ営業あり', 'wifiあり'],
    url: 'https://www.hotpepper.jp/strJ001219010/?vos=nhppalsa000016',
  },
  {
    id: 'J000015290',
    title: '甘太郎 横浜北幸店',
    area: '神奈川 横浜 横浜駅',
    genre: '焼肉・ホルモン',
    subgenre: '居酒屋',
    budget: '2500円',
    catchword: '☆居酒屋メニュー☆ 少人数から団体様まで♪',
    tags: ['コース有り', 'wifiあり'],
    url: 'https://www.hotpepper.jp/strJ000015290/?vos=nhppalsa000016',
  },
  {
    id: 'J000019233',
    title: '甘太郎 千葉センシティ店',
    area: '千葉 千葉・稲毛 千葉駅',
    genre: '居酒屋',
    subgenre: '和食',
    budget: '2500円',
    catchword: '少人数から座れる夜景席 ☆居酒屋メニュー☆',
    tags: ['コース有り', 'ランチ営業あり', 'wifiあり'],
    url: 'https://www.hotpepper.jp/strJ000019233/?vos=nhppalsa000016',
  },
  {
    id: 'J000768703',
    title: '温石 左近太郎 本店',
    area: '京都 河原町・木屋町 河原町三条',
    genre: '和食',
    subgenre: '居酒屋',
    budget: '【ランチ】2,500円より　【ディナー】3,800円より',
    catchword: '顔合わせや還暦のお祝いに 京町家で旬食材の創作和食',
    tags: ['コース有り', 'ランチ営業あり', 'wifiあり'],
    url: 'https://www.hotpepper.jp/strJ000768703/?vos=nhppalsa000016',
  },
  {
    id: 'J000042611',
    title: '甘太郎 川崎駅前リバーク店',
    area: '神奈川 川崎・鶴見 川崎',
    genre: '居酒屋',
    subgenre: '焼肉・ホルモン',
    budget: '2500円',
    catchword: '少人数から座れる夜景席★ ☆居酒屋メニュー☆',
    tags: ['コース有り', 'wifiあり'],
    url: 'https://www.hotpepper.jp/strJ000042611/?vos=nhppalsa000016',
  },
];

export default shopData